#!/bin/bash

FILE=$1
[ -r "$FILE" ] || exit 1

arr=()
for (( i = 0; i < 3; i++ )); do
  read a
  arr[${#arr[@]}]=$a
done <"$FILE"

USER=${arr[0]}
PASS=${arr[1]}
BLB_IP=${arr[2]}
pass=$(echo -n "$PASS" | md5sum | cut -d ' ' -f 1)

try_login () {
  local nonce=$1
  local encoded=$(echo -n "$USER:$pass:$nonce" | md5sum | cut -d ' ' -f 1)
  local pstr="encoded=$USER%3A$encoded&nonce=$nonce&goto=Login&URL=%2F"

  local submit="http://$BLB_IP/webconf/WCFContainer.html?encoded=$USER"
  # order of cookies matters!
  local cookies="language=fr; auth=$nonce; connected=true"
  local failed="\* File Name   : logon.htm"
  if curl -d "$pstr" -b "$cookies" "$submit" 2>/dev/null \
      | grep -q "$failed"; then
    return 1
  else
    return 0
  fi
}

get_nonce () {
  local home="http://$BLB_IP/webconf/openappliance_index.html"
  curl "$home" 2>/dev/null | grep 'input.*name="nonce"' \
    | sed 's/.*value="\([^"]\+\)".*/\1/'
}

nonce=$(get_nonce)
if try_login "$nonce"; then
  # login succeeded
  echo -n "$nonce"
  exit 0
fi

# login failed
exit 1

