#!/bin/sh

rm -f /var/www/archive/restore/data/status
wget --no-check-certificate http://192.168.0.101/restore/$( cat /opt/vyatta/etc/vmmeta )/data -O /tmp/data
mkdir -p /var/www/archive/restore/data/status/