#!/bin/sh

rm -f /var/www/archive/restore/conf/status
wget --no-check-certificate http://$( cat /tmp/dom0 )/restore/domU-test/conf -O /tmp/config
/bin/bash --rcfile /etc/bash_completion -i -c "/opt/vyatta/sbin/vyatta-load-config.pl /tmp/config"
mkdir -p /var/www/archive/restore/conf/status/