#!/bin/sh

rm -f /var/www/archive/restore/data/status
wget --no-check-certificate http://192.168.0.101/restore/$( cat /opt/vyatta/etc/vmmeta )/data -O /tmp/data
mkdir -p /var/www/archive/restore/data/status/
echo '<?xml version="1.0" encoding="utf-8"?><openappliance><token></token><error><code>0</code><msg></msg></error></openappliance>'
