#!/bin/bash

rm -f /var/www/archive/restore/conf/status

sudo wget --no-check-certificate http://192.168.0.101/restore/$( cat /opt/vyatta/etc/vmmeta )/conf -O /opt/vyatta/etc/config/config.boot

sudo chgrp vyattacfg /opt/vyatta/etc/config/config.boot          

sudo chmod 660 /opt/vyatta/etc/config/config.boot 

source /etc/bash_completion 
/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper begin 
/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper load 
/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper end 

mkdir -p /var/www/archive/restore/conf/status/
echo '<?xml version="1.0" encoding="utf-8"?><openappliance><token></token><error><code>0</code><msg></msg></error></openappliance>'
